require("core.plugin_config.colorizer")
require("core.plugin_config.colors")
require("core.plugin_config.conform")
require("core.plugin_config.fugitive")
require("core.plugin_config.harpoon")
require("core.plugin_config.lsp")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.template-string")
--require("core.plugin_config.trouble")
require("core.plugin_config.undotree")
require("core.plugin_config.whichkey")
-- require("core.plugin_config.toggleterm")
-- require("core.plugin_config.fidget")
-- require("core.plugin_config.lspkind")
-- require("core.plugin_config.noice")
